const {protectedTool}=require('./protected-tool');

function registerCRMTools(service,pool){
 service.register({name:'search_customer',permission:'contacts.read',confidence:.98,execute:async(input,ctx)=>{const q=String(input.query||'').trim();if(!q)throw Error('query is required');const r=await pool.query('SELECT id,name,email,phone FROM contacts WHERE tenant_id=$1 AND deleted_at IS NULL AND (name ILIKE $2 OR email ILIKE $2 OR phone ILIKE $2) LIMIT 20',[ctx.tenant_id,`%${q}%`]);return r.rows}});
 service.register({name:'search_products',permission:'products.read',confidence:.98,execute:async(input,ctx)=>{const q=String(input.query||'').trim();const r=await pool.query('SELECT id,name,sku,price,description FROM products WHERE tenant_id=$1 AND deleted_at IS NULL AND (name ILIKE $2 OR sku ILIKE $2) LIMIT 20',[ctx.tenant_id,`%${q}%`]);return r.rows}});
 const taskTool={name:'create_task',permission:'tasks.create',confidence:1,execute:async(input,ctx)=>{if(!input.title)throw Error('title is required');const r=await pool.query('INSERT INTO tasks(tenant_id,assigned_user_id,title,description,priority,due_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,title,status,priority,due_at',[ctx.tenant_id,input.assigned_user_id||ctx.user_id,input.title,input.description||null,input.priority||'normal',input.due_at||null]);return r.rows[0]}};
 service.register(pool ? protectedTool({tool:taskTool,action:'create_task',pool}) : taskTool);
 const leadTool={name:'create_lead',permission:'leads.create',confidence:1,execute:async(input,ctx)=>{if(!input.name)throw Error('name is required');const r=await pool.query('INSERT INTO leads(tenant_id,name,company,email,phone,source) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,company,email,phone,stage,score',[ctx.tenant_id,input.name,input.company||'',input.email||null,input.phone||null,input.source||null]);return r.rows[0]}};
 service.register(pool ? protectedTool({tool:leadTool,action:'create_lead',pool}) : leadTool);
 const updateLeadTool={name:'update_lead',permission:'leads.edit',confidence:1,execute:async(input,ctx)=>{if(!input.lead_id)throw Error('lead_id is required');const allowed=['name','company','email','phone','stage','score','status'];const fields=Object.keys(input).filter(k=>allowed.includes(k));if(!fields.length)throw Error('no editable fields');const values=fields.map(k=>input[k]),set=fields.map((k,i)=>`${k}=$${i+1}`).join(',');const r=await pool.query(`UPDATE leads SET ${set},updated_at=now() WHERE id=$${fields.length+1} AND tenant_id=$${fields.length+2} AND deleted_at IS NULL RETURNING id,name,company,email,phone,stage,score,status`,[...values,input.lead_id,ctx.tenant_id]);if(!r.rows[0])throw Error('lead not found');return r.rows[0]}};
 service.register(pool ? protectedTool({tool:updateLeadTool,action:'update_lead',pool}) : updateLeadTool);
 service.register({name:'get_customer_history',permission:'contacts.read',confidence:1,execute:async(input,ctx)=>{if(!input.contact_id)throw Error('contact_id is required');const [contact,opps,convs,tasks]=await Promise.all([pool.query('SELECT id,name,email,phone FROM contacts WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL',[input.contact_id,ctx.tenant_id]),pool.query('SELECT id,name,stage,amount,probability FROM opportunities WHERE contact_id=$1 AND tenant_id=$2 AND deleted_at IS NULL',[input.contact_id,ctx.tenant_id]),pool.query('SELECT id,subject,status,last_message_at FROM conversations WHERE contact_id=$1 AND tenant_id=$2 AND deleted_at IS NULL ORDER BY last_message_at DESC LIMIT 20',[input.contact_id,ctx.tenant_id]),pool.query('SELECT id,title,status,priority,due_at FROM tasks WHERE tenant_id=$1 AND deleted_at IS NULL AND opportunity_id IN (SELECT id FROM opportunities WHERE contact_id=$2 AND tenant_id=$1) ORDER BY due_at DESC LIMIT 20',[ctx.tenant_id,input.contact_id])]);return {contact:contact.rows[0]||null,opportunities:opps.rows,conversations:convs.rows,tasks:tasks.rows}}});
}
module.exports={registerCRMTools};
